# Generated by Django 2.1.1 on 2018-09-12 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SlackUser',
            fields=[
                ('user_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
    ]
