# Generated by Django 2.1.1 on 2018-09-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pointz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='slackuser',
            name='badges',
            field=models.ManyToManyField(related_name='users', to='pointz.Badge'),
        ),
    ]
