# Generated by Django 2.1.1 on 2018-09-19 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuotzSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_id', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='SlackUser',
            fields=[
                ('user_id', models.CharField(max_length=64, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='quotzsubscription',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='quotz.SlackUser'),
        ),
    ]
